### PR TITLE
Add uploads

### PR DESCRIPTION
**Pull request by willwhite**
Adds support for the [uploads api](https://www.mapbox.com/developers/api/uploads/).

### CODE REVIEW

**Comment by tmcw** [comment]
How do you feel about the S3 part of this? Should mapbox-sdk-js require aws-sdk and manage this for you, or should we just provide code samples that demonstrate integration?

**Comment by willwhite** [comment]
I'm learning towards keeping this a very light wrapper around the HTTP API (and small dependency tree especially for the browser). It seems like something higher level that could be added later or by another project. That said, I could be convinced either way.

**Comment by rclark** [comment]
> keeping this a very light wrapper around the HTTP API

:+1: IMO this SDK should provide the base-level building blocks and let service-specific tools handle higher-level niceties where needed.

**Comment by tmcw** [comment]
Yep, agree. The aws-sdk is also a very heavy dependency and not all users are going to use uploads.

**Pull request merged**
