### PR TITLE
Typescript Typings

### PR DESCRIPTION
**Pull request by mikeomeara1**
Added what I believe to be fairly complete and current Typescript Typings including the Isochrone API (see [PR#292](https://github.com/mapbox/mapbox-sdk-js/pull/292)). However, not everything has been fully tested.

Closes [#213](https://github.com/mapbox/mapbox-sdk-js/issues/213).

I think these should **probably** be submitted via PR to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) so it can flow into `@types` but [#213](https://github.com/mapbox/mapbox-sdk-js/issues/213) indicates you're soliciting a PR for this. 

If this isn't how you want to do it, just let me know.

- Added `types/index.d.ts` typescript typings
- Added  `"types" : "./types/index.d.ts"` to `package.json`
- Usage/TS Example: [https://gist.github.com/mikeomeara1/737c7133422cb29eb7eaac5b90be8882](https://gist.github.com/mikeomeara1/737c7133422cb29eb7eaac5b90be8882)

### CODE REVIEW

**Comment by davidtheclark** [comment]
See https://github.com/mapbox/mapbox-sdk-js/issues/213#issuecomment-445928802

I agree with your suggestion, @mikeomeara1, that TypeScript users maintain these definitions in DefinitelyTyped.

Thanks for sharing your work!

**Comment by mikeomeara1** [comment]
You got it @davidtheclark. I'll post a PR over there. 

Thanks!

Mike

**Comment by eventualbuddha** [comment]
@mikeomeara1 doesn't look like the PR ever got created at DefinitelyTyped. Need a hand?

**Comment by mikeomeara1** [comment]
@eventualbuddha You're correct I started to put that together then got sidetracked. If you're interested in putting that together, I'm all about it. 

I may need to back down the Isochrone API types that are in there because that API is not actually in the SDK yet (pending [PR#292](https://github.com/mapbox/mapbox-sdk-js/pull/292)). Otherwise, I think we're probably pretty close on that one. Just needs to get packaged up and pr-ed to ~DT (I think).

**Comment by ianldgs** [comment]
I could help with this. Shouldn't take long to create a folder and make a PR.

There is only one thing I'm not sure about:
How should we name the folder on DT? NPM package is `@mapbox/mapbox-sdk`, and there is also a `@types/mapbox` (for NPM package `mapbox.js`).
Probably `@types/mapbox-sdk`?
Note: vscode suggests: "Try `npm install @types/mapbox__mapbox-sdk` if it exists", but naming like this looks really weird to me.

**Comment by a-pavlov-parc** [comment]
@ianldgs @types/mapbox__mapbox-sdk will work

**Comment by jeffbdye** [comment]
I've just contributed types to DefinitelyTyped with the below PR, based loosely on the types from @mikeomeara1 and adjusted into ambient modules. They're available with the expected package name, `@types/mapbox__mapbox-sdk`. There might still be some cleaning up to do of the various service response body objects, but I'm using the directions types in my own project and they're working as expected!

See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37176 for reference.

**Comment by mikeomeara1** [comment]
@jeffbdye Thanks so much for running with that! 

We'll pull those types into our project shortly. We're currently using the types for Directions, Geocoding, Static Maps and Iscochrone. All seem to be working as well.

Thanks again!

**Comment by pmabres** [comment]
I've encountered just one issue with the typings. 
for reverse Geocoding, the assertion type checks for v.coordinates wich itself checks for v.tuple(number,number)

https://github.com/mapbox/fusspot#vtuplevalidators
A "tuple" is an array with a fixed number of items, each item with its own specific type. One common example of a tuple is coordinates described by a two-item array, [longitude, latitude]. 

In the typings the query appears with the type LatLngLike

**Comment by jeffbdye** [comment]
Hey @pmabres, I've since added these types to `@types` (see PR below) and they might still have that issue you'd described. Any PRs/improvements to those types would be much appreciated!

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37176

**Comment by boredland** [comment]
> Any PRs/improvements to those types would be much appreciated!

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59374

I don't know who to address, but mapbox sdk should move to Typescript. Typescript's rise to triumph may not have been completely obvious in 2019, but it is today.

**Comment by jpike88** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/62116

The types are out of sync with mapbox rendering them next to useless. It would be nice for the mapbox team to maintain types internally to prevent this issue from existing indefinitely.

**Pull request closed without merging**
