### PR TITLE
add geocoder bbox param

### LINKED ISSUE #90: Support geocoding bbox parameter

### PR DESCRIPTION
**Pull request by mattficke**
Fixes #90. Could use 👀 to make sure this is all structured correctly.

### CODE REVIEW

**Comment by mattficke** [comment]
@tmcw let me know if this looks ok.

**Comment by tmcw** [comment]
I think this'll need inclusion in the URL template as well https://github.com/mapbox/mapbox-sdk-js/blob/master/lib/constants.js#L6

**Comment by mattficke** [comment]
@tmcw 👍, added.

**Comment by pichot** [comment]
Would love to see this merged.

**Pull request merged**
