### PR TITLE
Revitalization

### PR DESCRIPTION
**Pull request by davidtheclark**
Addresses #211.

This branch can serve as the base branch for revitalization work. In this initial commit, I've transferred code over from our internal prototype. Follow-ups can be PRs into this branch.

The diff isn't going to be useful, because the codebase is completely replaced. So please pull down the branch and look around, and share your feedback!

A few details about the codebase:

- All the syntax is ES5-compatible, so we don't have to worry about a compilation step (which is especially nice in early stages of development).
- MD files in `docs/` are generated by documentation.js from code comments.
- Unit tests are in `__tests__/` directories next to the files they test. Integration tests are in `test/`. `test-shared-interface.js` includes integration tests that are run against both Node and browser clients.
- There's a little CLI in `test/try-node.js` that we can use to check responses when adding new services and service methods. We could also build something for the browser, but that might be more work.
- The `"browser"` field in `package.json` should instruct bundlers targeting the browser to use the browser client instead of the Node client. (I've tried this out, and seems to work fine.)
- Prettier formats the JS, remark formats the MD.

(@kepta @emilymdubois — FYI: In creating this branch, I've made some changes to directory structure to take advantage of the new setting. I hope it's a little better organized now. Also, I refactored the validators some, hoping to make its usage a little more straightforward.)

**TODO**

- [x] Add services to cover everything that is already covered by the public SDK. (@tristen were you interested in helping out with this step?). Below is a checklist for the existing SDK methods that we'll need equivalents for
  - [x] MapboxStyles @davidtheclark
      - [x] listStyles
      - [x] createStyle
      - [x] updateStyle
      - [x] deleteStyle
      - [x] readStyle
      - [x] readSprite
      - [x] readFontGlyphRanges
      - [x] addIcon
      - [x] deleteIcon
      - [x] embedStyle
  - [x] MapboxStatic @davidtheclark
      - [x] getStaticURL
      - ~[ ] getStaticClassicURL~
  - [x] MapboxUploads @kepta
      - [x] listUploads
      - [x] createUploadCredentials
      - [x] createUpload
      - [x] readUpload
      - [x] deleteUpload
  - [x] MapboxDatasets @davidtheclark
      - [x] listDatasets
      - [x] createDataset
      - [x] readDataset
      - [x] updateDataset
      - [x] deleteDataset
      - [x] listFeatures
      - [x] insertFeature
      - [x] readFeature
      - [x] deleteFeature
  - [x] MapboxTilesets @davidtheclark
      - [x] tilequery
      - [x] listTilesets
  - [x] MapboxGeocoding @davidtheclark
      - [x] geocodeForward
      - [x] geocodeReverse
  - [x] MapboxDirections @kepta
      - [x] getDirections
  - [x] MapboxMatching @kepta
      - [x] matching
  - [x] MapboxMatrix @kepta
      - [x] getMatrix
  - [x] MapboxTokens @davidtheclark
      - [x] listTokens
      - [x] createToken
      - [x] createTemporaryToken
      - [x] updateTokenAuthorization
      - [x] deleteTokenAuthorization
      - [x] retrieveToken
      - [x] listScopes
  - ~[ ] MapboxTilestats @emilymdubois~
      - ~[ ] getTilestats~
      - ~[ ] putTilestats~
  - ~[ ] MapboxSurface~
      - ~[ ] surface~
- [x] Gather feedback on everything (interface, documentation, implementation). *So please share your feedback :)*
- [x] Ensure this package integrates smoothly with Mapbox's internal client.
- [x] Explore creation of service clients without first creating a base client.
- [x] Add build process for file consumable via `unpkg.com` (discussed below).

Anybody have todos in mind?

cc @danswick @nitaliano

### CODE REVIEW

**Comment by davidtheclark** [comment]
@tristen There is not currently a running list. We could make one, though, and add it to the TODOs above. Should be pretty straightforward to follow the patterns for the current services in `services/`, and let me know if you have any questions.

**Comment by andrewharvey** [comment]
To be clear, logistically this PR won't be merged for until it's ready to replace the current mapbox-sdk-js right?

Work on `revitalized` will be done branched from `revitalized`, with new PRs against `revitalized`, which can be merged as usually, and then finally once `revitalized` is ready for production this PR is merged.

Is that the plan?

**Comment by andrewharvey** [comment]
> The "browser" field in package.json should instruct bundlers targeting the browser to use the browser client instead of the Node client. (I've tried this out, and seems to work fine.)

Something like https://github.com/mapbox/mapbox-sdk-js/blob/master/package.json#L16 would be nice. At the moment web developers without a build system can just script include `https://unpkg.com/mapbox@1.0.0-beta10/dist/mapbox-sdk.min.js`. Ideally then this would be published on the Mapbox CDN so it's easy to obtain alongside GL JS and other Mapbox libraries published to the CDN #216.

**Comment by andrewharvey** [comment]
> We'll punt on publication to api.mapbox.com, but could add it later. Setting up a build to allow people to consume it directly from unpkg.com sounds fine for now. @andrewharvey: Do you think these users want all the services bundled up and available on a global variable?

All services in one bundle. It's simpler and anyone who wants to optimize delivery can use their own build workflow. This is how `turf` does it.

**Comment by kepta** [comment]
@davidtheclark I noticed that calling [`.send`](https://github.com/mapbox/mapbox-sdk-js/blob/985d01feddbff3edfe9a1dedec58321c40c0d996/docs/classes.md#send) multiple times, sends multiple requests. Which contradicts what is said in the [`.clone`](https://github.com/mapbox/mapbox-sdk-js/blob/985d01feddbff3edfe9a1dedec58321c40c0d996/docs/classes.md#clone)
> Each request can only be sent once. 

I think we should explain a bit more of the following for `MapiRequest`:
1. What happens when you call `.send()` more than once.
2. What happens when you call `.abort()` more than once.
3. How does `.eachPage` signal `done`?

**Comment by davidtheclark** [comment]
Added a checklist to the initial comment with services & service methods we'll need to port. I put my name next to a few that I plan to deal with soon. If anybody is interested in porting a service, please add your name next to it so we don't duplicate work.

**Comment by kepta** [comment]
Added myself to MapboxDirections, MapboxMatching, MapboxMatrix

**Comment by davidtheclark** [comment]
I cut the Surface API from the list of services to port because it's no longer publicly documented.

**Comment by davidtheclark** [comment]
I feel like we should do the same with tilestats. Do you disagree @emilymdubois? I was thinking maybe we should only include publicly documented APIs. Anything else should effectively be considered internal.

**Comment by emilymdubois** [comment]
@davidtheclark 👍 Agreed. I've crossed out the tilestats methods in the OP.

**Comment by davidtheclark** [comment]
🐻🐻🐻

We've ported all the services from the legacy SDK. So I think this is just about ready to go.

- @andrewharvey @nitaliano would you like to experiment with this branch before we merge it into master? Your feedback would be appreciated. Bug reports welcome, but the most important feedback at this point is about overall structure and user-facing interface.
- I'll take one final pass confirming that this works as expected as a base for our internal client.

**Comment by nitaliano** [comment]
I'll pull this branch today and update all my RN demos and let you know how it goes!

**Comment by nitaliano** [comment]
@davidtheclark I'm running into this right now, I'll debug more tomorrow. This should be simple to resolve.

screenshot 2018-06-06 16 55 16

**Comment by davidtheclark** [comment]
@nitaliano Updated the parse-mapbox-token dependency so this is ready for another shot on React NAtive.

**Comment by nitaliano** [comment]
@davidtheclark just did a test run with the directions API and it working 😃 

screenshot 2018-06-07 11 18 57

**Comment by davidtheclark** [comment]
I'll plan to release this early next week. If anybody has any concerns or feedback please try to voice it within the next few days.

**Comment by davidtheclark** [comment]
> We should try to go through all the open tickets and see if they are still an issue for the new library

Good idea. I looked at them when I started development but haven't look for a while — I'll do that before releasing.

**Comment by davidtheclark** [comment]
To address https://github.com/mapbox/mapbox-sdk-js/issues/125, we should add a `datasetUrl` to the  `Uploads#createUpload` function (in addition to `s3Url`, and user must provide one of them). @kepta interested in making that change?

**Comment by davidtheclark** [comment]
Hm, I'm not sure if `datasetUrl` is the right thing. Maybe just dataset ID? I'm not sure off the top of my head whether you'd ever be able to access another account's datasets. Needs some investigating.

**Pull request merged**
