### PR TITLE
add tokens api support

### LINKED ISSUE #143: Tokens API support

### PR DESCRIPTION
**Pull request by andrewharvey**
Closes #143

~~I'd still like to do some more testing to and try to add more unit tests to ensure it's rock solid before merging.~~

### CODE REVIEW

**Comment by andrewharvey** [comment]
This one should be good for a review now.

**Comment by andrewharvey** [comment]
The CI failures here are coming from uploads, so unrelated to this branch. The tokens tests and linting are passing.

**Comment by andrewharvey** [comment]
It might be useful to expose the [token format](https://www.mapbox.com/api-documentation/#the-token-format) components as part of this.

lib/get_user.js currently extracts the user, but other methods could abstract determining token type, extracting authorization id (or authorization object for tk)

**Comment by andrewharvey** [comment]
I've manually rebased this to accommodate the changes from #160

**Comment by scothis** [comment]
@andrewharvey added a commit that cleans a few things up and make a couple other bigger lifts across the code base. Mostly with regards to how access tokens are applied to URLs.

**Comment by andrewharvey** [comment]
@scothis Thanks, looks good to me. Anything else needed to get this merged?

**Comment by scothis** [comment]
@andrewharvey thanks for the contribution

**Pull request merged**
